version: "3"
services:
  git-sync:
    build: .
    # image: markushinz/markushinz/git-sync:latest
    restart: always
    environment:
      - GIT_REPOSITORY=https://github.com/markushinz/git-sync.git
      # - GIT_BRANCH=master
      # - SYNC_INTERVAL=60
    volumes:
      - ./git-sync:/mnt/git-sync
